services:
  whisper-wrap:
    build: .
    image: whisper-wrap:latest
    container_name: whisper-wrap
    ports:
      - "${API_PORT:-8000}:${API_PORT:-8000}"
    environment:
      - API_PORT=${API_PORT:-8000}
      - API_HOST=${API_HOST:-0.0.0.0}
      - WHISPER_SERVER_PORT=${WHISPER_SERVER_PORT:-9000}
      - WHISPER_SERVER_HOST=${WHISPER_SERVER_HOST:-localhost}
      - MAX_FILE_SIZE_MB=200
      - TEMP_DIR=/tmp/whisper-wrap
      - LOG_LEVEL=INFO
      - UPLOAD_TIMEOUT_SECONDS=60
    volumes:
      - whisper_models:/whisper.cpp/models  # Persist downloaded models (1.5GB)
      # Note: /tmp/whisper-wrap uses container's tmpfs for automatic cleanup
    restart: unless-stopped

volumes:
  whisper_models:
    driver: local