services:
  whisper-wrap:
    build: .
    ports:
      - "8000:8000"
    environment:
      - MAX_FILE_SIZE_MB=200
      - TEMP_DIR=/tmp/whisper-wrap
      - LOG_LEVEL=INFO
      - UPLOAD_TIMEOUT_SECONDS=60
    volumes:
      - /tmp/whisper-wrap:/tmp/whisper-wrap
    restart: unless-stopped