services:
  whisper-wrap:
    build: .
    ports:
      - "8000:8000"
    environment:
      - MAX_FILE_SIZE_MB=200
      - TEMP_DIR=/tmp/whisper-wrap
      - LOG_LEVEL=INFO
      - UPLOAD_TIMEOUT_SECONDS=60
    volumes:
      - whisper_models:/whisper.cpp/models  # Persist downloaded models (1.5GB)
      # Note: /tmp/whisper-wrap uses container's tmpfs for automatic cleanup
    restart: unless-stopped

volumes:
  whisper_models:
    driver: local